project:
  type: website
  output-dir: docs

website:
  title: "hsin-yu-yang.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/hsin-yu-yang
        
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

